
// Objective-C API for talking to the following Go packages
//
//	lukechampine.com/us-bindings/gomobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Us_FRAMEWORK_H__
#define __Us_FRAMEWORK_H__

#include "Us.objc.h"
#include "Universe.objc.h"

#endif
